### ISSUE TITLE
打开app出现mihoyo的logo, 白屏, 然后闪退

### ISSUE THREAD

**Issue by BinxWine** [Coulin9/YuanShen_launcher_mac_porting#10]

**Comment by BinxWine** [comment]
M1 pro, 32G, macos15

**Comment by Coulin9** [comment]
需要block掉米哈游的一些域名，b站有具体的教程【【Mac玩原神】一招解决Mac玩原神5.1所有报错问题/原神5.1/Mac玩原神/Mac使用crossover/原神报错问题解决方案/gptk2/Mac玩游戏-哔哩哔哩】 https://b23.tv/aYC1Gwf
